version: "3.7"
services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    restart: always
    ports:
     - "5001:5001"
    depends_on:
      - redis
      - rabbitmq
    volumes: ['./api:/api']
    environment:
      MQ_URL: amqp://guest:guest@rabbitmq:5672/0
      MQ_EXCHANGE: ratelimiting
  worker:
    build:
      context: ./celery-queue
      dockerfile: Dockerfile
    command: celery -A tasks worker -l info -E
    environment:
      # CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672/0
      MQ_URL: amqp://guest:guest@rabbitmq:5672/0
      MQ_EXCHANGE: ratelimiting
    depends_on:
      - redis
      - rabbitmq
    volumes: ['./celery-queue:/queue']
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:alpine
    ports:
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_VHOST: 0
